### ISSUE TITLE
OAuth code upgrade is incomplete

### ISSUE THREAD

**Issue by fbonzon** [basvandorst/StravaPHP#21]
#18 recently upgraded dependency [league/oauth2-client](https://github.com/thephpleague/oauth2-client) from 0.8.1 to 1.4.2. That old version was an alpha one, and the abstract methods to implement changed in the final release 1.0.

Specifically, `getUser*()` methods were [removed](https://github.com/thephpleague/oauth2-client/commit/9284fdf) on 9 May 2015, and some of the new ones are left unimplemented here, e.g. `createResourceOwner()`. This is messy and should be fixed. I can take care of this.

`userUid()`, `userEmail()`, `userScreenName()` methods should be deprecated here, and removed in the next major release. The code to implement for the new methods is already available in [Edwin-Luijten/oauth2-strava](https://github.com/Edwin-Luijten/oauth2-strava). We could copy it here (MIT license allows it), or make this package depend on it. Any preference?

**Comment by qligier** [comment]
Yep, really messy :yum: 
Replacing [league/oauth2-client](/thephpleague/oauth2-client) with [edwin-luijten/oauth2-strava](/Edwin-Luijten/oauth2-strava) is imho the best solution.

**Comment by fbonzon** [comment]
Agree with @qligier. In my fork of this project, I did use [edwin-luijten/oauth2-strava](https://github.com/Edwin-Luijten/oauth2-strava) instead of the local implementation here. It's been running successfully in production for a few weeks already. I'm happy to make a PR, once earlier #22 is approved.

**Comment by vredeling** [comment]
Adding the Strava provider from edwin-luijten/oauth2-strava sounds like a good idea.
