### ISSUE TITLE
Uploading gpx file

### ISSUE THREAD

**Issue by ghost** [basvandorst/StravaPHP#23]
actual_file = realpath('Giro_mattutino.gpx');
 $file ='@'.$actual_file;
 $client->uploadActivity($file, 'ride', 'Morning Ride', 'A test', 0, 1, 'gpx');

I'm using this code to upload the file but it doesn't seem to work.. Any help?

**Comment by harhoo** [comment]
I think this is possibly broken under PHP 5.6 and greater.

Basically, for Curl to upload files now, you need to use curl_file_create (or new CurlFile). However, Pest doesn't recognise this as multipart, so ends up up running http_build_query on the data.

So this works for me:

$path = realpath('file.tcx');
$path = new \CurlFile($path, null, basename($path));
return $client->uploadActivity($path,  'ride', 'Morning Ride', 'A test', 0, 1, 'tcx');
        
IF I change line 379 of Pest.php to multipart=true. Other than that, no luck at the moment.

**Comment by vredeling** [comment]
I completely agree about replacing pest with guzzle. Deserves a new issue # I think.

**Comment by vredeling** [comment]
Voila: #43

**Comment by vredeling** [comment]
#43 is done. We'll have to check if file uploads work as expected. @harhoo could you try this?

**Comment by vredeling** [comment]
Outdated, closing
