### ISSUE TITLE
Full Leaderboards

### ISSUE THREAD

**Issue by Ramon1987** [basvandorst/StravaPHP#26]
Hi, 

- is it possible to show more than 10 people on a leaderboard of a segment? 
- Is it possible to show a leaderboard without the athlete en the -2 and +2 atheletes who is connected?

Keep up the good work!

**Comment by basvandorst** [comment]
> is it possible to show more than 10 people on a leaderboard of a segment?

Yes, it possible to show more than 10 people. Use the` $per_page` parameter.

> Is it possible to show a leaderboard without the athlete en the -2 and +2 atheletes who is connected?

No, as far as I know this isn't possible with the [segment endpoint](https://strava.github.io/api/v3/segments/#leaderboard) of the Strava API
