### ISSUE TITLE
Routes and Route streams support

### ISSUE THREAD

**Issue by hamazaspavetisyan** [basvandorst/StravaPHP#30]
Please add support for getting routes and route streams.

GET https://www.strava.com/api/v3/routes/:route_id
GET https://www.strava.com/api/v3/routes/:id/streams
GET https://www.strava.com/api/v3/athletes/:id/routes

**Comment by basvandorst** [comment]
Introduced 3 new methods: 
```
$client->getAthleteRoutes($id, $type = null, $after = null, $page = null, $per_page = null);
$client->getStreamsRoute($id);
$client->getRoute($id);
```

Currently only available in master but I will create a new tag this week.

**Comment by hamazaspavetisyan** [comment]
Thanks
