### ISSUE TITLE
Null is returned when I try to get athlete or the activities

### ISSUE THREAD

**Issue by m7vm7v** [basvandorst/StravaPHP#37]
Hi everyone,

Many thanks for your time spending in this issue.
I am following all the steps and and I do receive a proper respond from strava and I do have the user_token, strava_user_id so all the credentials are fine. And after I check the user in Strava I do see my new application in My Apps. I have 2 old activities and 1 from today.

But I receive null when I 
`$adapter = new Pest('https://www.strava.com/api/v3');
        $service = new REST('the_token', $adapter);  // Define your user token here.
        $client = new Client($service);
print_r($client->getAthlete()); //null
        print_r($client->getAthleteActivities()); //null`

Do you have any idea do I miss anything or the API has changed as a few mounts ago it was working fine. 

Thanks

**Comment by maltehuebner** [comment]
I submitted a quick fix in #45.

**Comment by vredeling** [comment]
This issue is no longer relevant since moving from Pest to GuzzleHTTP I believe. Also #45 and subsequent commits resolve NULL results.

This issue can be closed imho.
