### ISSUE TITLE
getStreamsRoute returns null.

### ISSUE THREAD

**Issue by paullb514** [basvandorst/StravaPHP#39]
I'm not sure if this is an issue with the library or Strava but the getStreamsRoute is returning null. Doing some dumping, it appears as thought the URL being called is returning a 301 even though it is correct according to the Strava documentation.  (I confirmed the ID being called was valid via the Strava website)

**Comment by fbonzon** [comment]
We need to check. Thanks for reporting.

**Comment by paullb514** [comment]
Culprit was a trailing slash. Added fix in Pull request #41
