### ISSUE TITLE
Throws deprecated warning on php 7.1

### ISSUE THREAD

**Issue by uniquexor** [basvandorst/StravaPHP#40]
mcrypt has been deprecated since php 7.1 and this package throws a warning when trying to call OAuth::getAuthorizationUrl method. As I can see this method is defined in one of the dependencies, so it probably will not be a quick fix?.. :/

**Comment by fbonzon** [comment]
We should then upgrade the dependencies. Will take a look.

**Comment by vredeling** [comment]
This should no longer be a problem in league/oauth2-client  >= 2.0.

**Comment by vredeling** [comment]
Fixed
