### ISSUE TITLE
base_uri

### ISSUE THREAD

**Issue by BartJansseune** [basvandorst/StravaPHP#47]
$adapter = new \GuzzleHttp\Client(['base_uri' => 'https://www.strava.com/api/v3']);
should be with trailing /:
$adapter = new \GuzzleHttp\Client(['base_uri' => 'https://www.strava.com/api/v3/']);

**Comment by GMX9** [comment]
Yes , this fixed an issue for me, this will always return 404 error if does not take BartJansseune fix

**Comment by lasdou** [comment]
Me too ! exemples must be updated or code have changed.

**Comment by vredeling** [comment]
see #44 and #48

**Comment by vredeling** [comment]
This issue has been resolved in the latest release (^1.3.1)
