### ISSUE TITLE
Email is no longer available from Strava

### ISSUE THREAD

**Issue by fbonzon** [basvandorst/StravaPHP#52]
From the official [Strava V3 API Changelog](https://developers.strava.com/docs/changelog/):
> January 17, 2019
> Removed email from athlete summary and athlete detail.

We need to deprecate and eventually remove the functions returning an athlete's email.

**Comment by vredeling** [comment]
Yes, this is quite important. My Drupal client using this library is not working at the moment. Also we need to update the way we fetch and refresh authentication tokens. see: https://developers.strava.com/docs/oauth-updates/

**Comment by MAsifOfficial** [comment]
Is there any update on this?

**Comment by martynwheeler** [comment]
Does this still use forever tokens?

**Comment by MAsifOfficial** [comment]
Umm.. I've to integrate strava into a client's web app and it's my first time doing so. I'm just trying to wrap my head around this stuff, therefore not really sure about it.

**Comment by vredeling** [comment]
> Does this still use forever tokens?

yes, it still uses permanent tokens.

**Comment by martynwheeler** [comment]
Is it going to be a difficult job to move to the new system? I am not sure I fully understand the documentation.

**Comment by bymayo** [comment]
The easiest way to get the n `Refresh Tokens` is to use the new scope rules. Using old scope rules only brings back 'Forever Tokens'.

So instead of the old scopes:

```
$authUrl = $oauth->getAuthorizationUrl(
   [
      'scope' => [
         'public',
         // 'write',
         // 'view_private',
      ]
   ]
);
```

Use the new scopes:

```
$authUrl = $oauth->getAuthorizationUrl(
   [
      'scope' => [
           // 'read',
           // 'activity:read',
           // 'activity:write',
           // 'profile:write',
           'read_all',
           // 'activity:read_all',
           // 'profile:read_all',
           // 'view_private',
        ]
   ]
);
```

Then using the `getAccessToken` method like in the docs:

```
$token = $oauth->getAccessToken(
   'authorization_code',
   [
      'code' => $_GET['code']
   ]
);
```

This then gets a refresh token back and check if it's expired etc:

`$token->getRefreshToken()`

or 

`$token->getExpires()`

🎉

**Comment by martynwheeler** [comment]
Thank you, I (think) that I am already doing this.  But i see no documentation for getRefreshToken()???  Here is my code:
`
/**
     * @Route("/", name="homepage")
     */
    public function index(Request $request, StravaAPI $strava_api, RideData $rd)
    {
        //if code is set then grab and store
        if ($request->query->get('code')) {
            //'code' is set then grab the Strava token
            $token = $strava_api->getOAuth()->getAccessToken(
                'authorization_code',
                ['code' => $request->query->get('code')]
            );
            $request->getSession()->set('strava.token', $token->getToken());
        } elseif (($this->getUser() !=null) and ($request->getSession()->get('strava.token') == null)) {
            //User is logged in but no token is set then get authorization from Strava
            if ($this->getUser()->getStravaID() != null) {
                try {
                    $url = $strava_api->getOAuth()->getAuthorizationUrl([
                        'scope' => [
                            'read',
                            'activity:read',
                        ]
                    ]);
                } catch (Exception $e) {
                    print $e->getMessage();
                }
                return new RedirectResponse($url);
            }
        }

    public function getOAuth($url = 'homepage')
    {
        $options = [
            'clientId'     => getenv('STRAVA_ID'),
            'clientSecret' => getenv('STRAVA_SECRET'),
            'redirectUri'  => $this->urlGen->generate($url, [], UrlGeneratorInterface::ABSOLUTE_URL)
        ];
        $oauth = new OAuth($options);
        return $oauth;
    }
`

**Comment by bymayo** [comment]
@martynwheeler This plugin uses the oAuth Client dependency so you can use pretty much all methods from there:

https://github.com/thephpleague/oauth2-client/

**Comment by martynwheeler** [comment]
Would it be a good idea to incorporate https://github.com/Edwin-Luijten/oauth2-strava into the code?

**Comment by bymayo** [comment]
@martynwheeler You could probably use that instead, but then you don't get the methods to grab data easily. I've had no issues using this StravaPHP though once you just use the oAuth methods.

**Comment by MGatner** [comment]
@vredeling Can you provide a summary of what the outstanding issue is? Perusing this thread I haven't had any of the same problems in `v2` so far.

**Comment by vredeling** [comment]
@MGatner 

> _January 15, 2019_
> Email address is no longer part of the profile:read_all scope and is removed from the athlete model.

This means that if you have an app that links the account of the app to your Strava profile based on the email-address, you need to rework that relationship. Basically, that means going over the codebase and remove references to email as a Athlete property and any derivatives thereof.

**Comment by MGatner** [comment]
This doesn't appear to be an issue with the current library, as far as I can tell. No references to `email` anywhere. I have a hunch this won't apply to me at all, being a new user of the Strava API.

**Comment by vredeling** [comment]
I do think there is a problem with emails, https://github.com/basvandorst/StravaPHP/blob/01531f10091ba70772d95b56899ff2e38b72b8a0/src/Strava/API/OAuth.php#L80 for instance refers to a parent method that doesn't exist. Anyhoo, I'll have to dive into this myself.
