### ISSUE TITLE
Refresh Tokens Update

### ISSUE THREAD

**Issue by rjbathgate** [basvandorst/StravaPHP#57]
Hey

Am I right in thinking that the current code base doesn't support the Refresh Tokens Update, Strava announced a while back?

https://developers.strava.com/docs/oauth-updates/?utm_source=strava&utm_medium=mktgemail&utm_campaign=2018_10_15_API_update

From Oct 15th, the current "forever tokens" will be rejected, and they are moving to short lived refresh tokens.

Unless I'm not looking in the right place, the Auth process is only forever token based, with no provision for obtaining a refresh token and short lived access token.

Are there any plans to integrate this Strava change into this library?

Thanks

**Comment by rjbathgate** [comment]
This can be duly ignored; as I see it's all supported in the OAuth library. Sorry, should have looked properly first :-)

**Comment by brice81** [comment]
Hello,

could you explain how you solved this issue ? 

The code in the readme does not work anymore, and I did not found how to correct it.

Regards,
Brice
