### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by paha77** [basvandorst/StravaPHP#60]
I was wondering if the repo is still maintained or already abadoned?

**Comment by vredeling** [comment]
It feels quite abandoned, despite the occasional reply from @fbonzon

**Comment by vredeling** [comment]
Since it has been completely quiet here I promoted my fork to a full project and merged some PRs there. See: https://github.com/vredeling/StravaPHP and https://packagist.org/packages/vredeling/stravaphp

**Comment by basvandorst** [comment]
Sorry.. sorry.. guys, I wasn't active on Github for the last years!

@vredeling I'm not sure if a promoted fork / new repo is the best solution for abandoned projects. I have gave you admin access to this repo, so feel free to merge/change/fix/bump versions on this repo.

FYI: @fbonzon has already have full admin access to the repo for a while.

**Comment by vredeling** [comment]
@basvandorst Thanks for the invite. I'll do some general house-keeping and port my updates to this repo. And unpublish the fork and packagist repo.

@fbonzon has been occupied with other stuff too I guess. So it's been awfully quiet.

**Comment by basvandorst** [comment]
Cool @vredeling!

Thanks for all your effort and feel free to add your name to the
contributors list!

Op di 16 jun. 2020 17:52 schreef Bas Vredeling <notifications@github.com>:

**Comment by fbonzon** [comment]
Hi @paha77, hi @vredeling,

Thanks for your contributions to the PHP Strava API. It's great to see a community growing around it. Sorry for my silence. As you correctly guessed, I unfortunately wasn't able to dedicate time for it.
