### ISSUE TITLE
PHPUnit tests fail when running locally

### ISSUE THREAD

**Issue by djjavo** [basvandorst/StravaPHP#66]
Hi,

Not sure if this is the correct place to raise this, but I am running PHPUnit on master and getting failures on the following tests:

https://github.com/basvandorst/StravaPHP/blob/b30ce2d6c4383a34ebb521b1b27198a390f700ba/tests/Strava/API/Service/RESTTest.php#L502-L512

https://github.com/basvandorst/StravaPHP/blob/b30ce2d6c4383a34ebb521b1b27198a390f700ba/tests/Strava/API/Service/RESTTest.php#L514-L524

I'm getting the error `Trying to configure method "get" which cannot be configured because it does not exist, has not been specified, is final, or is static`

Would anyone be able to point me to the reason why it's failing locally but not on scrutinizer?

**Comment by djjavo** [comment]
Looks like the tests were flakey, and the code they were testing was wrong. Have submitted a fix for both in https://github.com/basvandorst/StravaPHP/pull/68

**Comment by vredeling** [comment]
Thanks for the patch, I've merged it last night.
