### ISSUE TITLE
Laravel 8 incompatibility

### ISSUE THREAD

**Issue by djjavo** [basvandorst/StravaPHP#69]
Laravel 8 requires the dependency of Guzzle `^7.0.1`, which conflicts with the version used in StravaPHP (Guzzle `~6.3`).
Could we please look into upgrading this, they have a guide here https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md#60-to-70.

**Comment by vredeling** [comment]
This will need to happen eventually anyway. So yes, let's do a quick scan of the outdated code so we have a sense of the scope. Looks quite involved at first glance.

**Comment by djjavo** [comment]
> The diff might look very big but 95% of Guzzle users will be able to upgrade without modification. Please see the upgrade document that describes all BC breaking changes.

It seems like the diff from 6.x to 7 looks large, but the actual changes to the implementation will be small

**Comment by djjavo** [comment]
The only issue I am seeing so far is on the `getRouteAsGPX` and `getRouteAsTCX` methods as `request()` should now return a `ResponseInterface`, whereas these apparently return a `String`.

**Comment by vredeling** [comment]
I'm using this library with Drupal exclusively and Drupal core 8 and 9 are using Guzzle 6. The upgrade to Guzzle 7 is [postponed to Drupal 10](https://www.drupal.org/project/drupal/issues/3104353). That will be released somewhere in the second half of 2022.
So for now I propose we use a different version number for tagging the Guzzle 7 version.

**Comment by vredeling** [comment]
@djjavo I've created a separate guzzle7 branch and updated packagist. You can require `basvandorst/stravaphp:^dev-guzzle` https://packagist.org/packages/basvandorst/stravaphp#dev-guzzle7
Hope that will suffice for now.

**Comment by vredeling** [comment]
@djjavo The Drupal upgrade path came earlier than expected. So I'm going to merge this into a 2.x release when I finally get around to fixing #21.
