### ISSUE TITLE
Can you do a point release?

### ISSUE THREAD

**Issue by picasticks** [basvandorst/StravaPHP#71]
Hi @vredeling, thanks for all the work on the library recently.

I just want to ask about your plans to do a version bump sometime soon, I have some code that depends on #64 and having a dependency on "dev-master" in my composer.json for so long is starting to give me unhappy feelings.

Thanks!

**Comment by vredeling** [comment]
Here you go: https://github.com/basvandorst/StravaPHP/releases/tag/1.5.0

**Comment by djjavo** [comment]
Does the new release need to be manually submitted to￼ https://packagist.org/packages/basvandorst/stravaphp?

**Comment by vredeling** [comment]
will have a look later today @djjavo @picasticks

**Comment by vredeling** [comment]
I manually updated the packagist package... was no longer being updated automatically, perhaps due to inactivity. will check at next release.

**Comment by picasticks** [comment]
Awesome, thanks!
