### ISSUE TITLE
Where is autoload.php

### ISSUE THREAD

**Issue by dineshnbhatia** [basvandorst/StravaPHP#73]
Every code shows to include "vendor/autoload.php"
is it missing in the library?

**Comment by vredeling** [comment]
It is generated when you run composer install.

**Comment by dineshnbhatia** [comment]
Thanks, @vredeling I have never used a composer. Anyway going through it found this site https://getcomposer.org will learn and implement it on my website. Let me know if any documentation or tutorial will help. Thanks again.
