### ISSUE TITLE
Wrong scopes in README.md code examples

### ISSUE THREAD

**Issue by mocniak** [basvandorst/StravaPHP#75]
Hi guys.

Maybe I'm missing something, but example code in README.md doesn't work because of the wrong scope names:

```
        print '<a href="'.$oauth->getAuthorizationUrl([
            // Uncomment required scopes.
            'scope' => [
                'public',
                // 'write',
                // 'view_private',
            ]
        ]).'">Connect</a>';
```

The right ones are `read, read_all, profile:read_all, profile:write, activity:read, activity:read_all, activity:write` as in https://developers.strava.com/docs/authentication/#detailsaboutrequestingaccess and replacing them in the example code fixed the bad request error I was getting.

Cheers!

**Comment by vredeling** [comment]
@mocniak thanks for noticing... Readme is now updated.
