### ISSUE TITLE
Incorrect parameter name for getSegmentEffort

### ISSUE THREAD

**Issue by AntonCooper** [basvandorst/StravaPHP#8]
$parameters = array(
            'bounds' => $athlete_id,
            'start_date_local' => $start_date_local,
            'end_date_local' => $end_date_local,
            'page' => $page,
            'per_page' => $per_page
        );

Should be:

        $parameters = array(
            'athlete_id' => $athlete_id,
            'start_date_local' => $start_date_local,
            'end_date_local' => $end_date_local,
            'page' => $page,
            'per_page' => $per_page
        );

**Comment by dsas** [comment]
This has been fixed by pull request 9 https://github.com/basvandorst/StravaPHP/pull/9

**Comment by basvandorst** [comment]
Thanks @dsas!

@AntonCooper This piece of code is now in the master branch. 
This weekend or next week I'm going to create and test the 1.1.0 branch.
