### ISSUE TITLE
GitHub Link Broken

### ISSUE THREAD

**Issue by MGatner** [basvandorst/StravaPHP#80]
The link associated with this repo is broken, "Server error": http://documentup.com/basvandorst/StravaPHP

**Comment by vredeling** [comment]
Changed it to https://github.com/basvandorst/StravaPHP
Seems a bit redundant, but at least it works. The documentation at the previous link seems to be removed completely.

@basvandorst Do you know why?

**Comment by vredeling** [comment]
Need to change the link in the main repo, not just in my fork 😵‍💫

**Comment by basvandorst** [comment]
According to this issue the project is not under active development anymore (+ he confirmed that the project itself is offline): https://github.com/jeromegn/DocumentUp/issues/113

Removed the associated link
