### ISSUE TITLE
Setup Packagist for automatic updates

### ISSUE THREAD

**Issue by MGatner** [basvandorst/StravaPHP#87]
Packagist is not set up for autoupdates so version 2 has not actually posted. Please turn on autoupdating (preferred) or at least force an update manually.

**Comment by djjavo** [comment]
@MGatner semi-related to versioning, I'd like to propose using semantic-release for this project. If you haven't used this before, it enforces specific commit messages and automates the creation of tags and releases on GitHub.

**Comment by vredeling** [comment]
I've manually updated the package just now. I'll change the ticket to set it up for auto-updates. But I'll have to do that later. Hope this helps you guys for now.

**Comment by MGatner** [comment]
@vredeling looks good, thank you!

@djjavo in my opinion semantic release is a big ask for random internet contributors. It works well with a team working on a closed project, but fi you're ever hoping to get contributions from occasional visitors then it breaks down. If you all decide to go that way I will gladly comply, just my two cents.

An alternative, GitHub's new "auto-generate release notes" feature works quite well and you can "massage" it to be close to semantic release. Here's a good article on it, but TL;DR you create **.github/release.yml** to map tags onto titles, etc: https://docs.github.com/en/enterprise-cloud@latest/repositories/releasing-projects-on-github/automatically-generated-release-notes

If the maintainers would like to go with GitHub's solution instead I would gladly accept "Triage" role to be able to tag my own PRs appropriately ;)

**Comment by vredeling** [comment]
I can't set up auto-updating as I'm not the owner of this project. @basvandorst can you please set it up?
https://packagist.org/about#how-to-update-packages

**Comment by vredeling** [comment]
Regarding the release notes: I've added a stub release.yml in e4f65a48bc1c00b27481ae972ce3d55a38c46dc8

**Comment by basvandorst** [comment]
Fixed.

Really nice to see that you guys will bring this package to a next level, great job @vredeling @MGatner, really appreciate it!

**Comment by MGatner** [comment]
@basvandorst May I petition you to elevate privileges for @vredeling in the interest of expediting future development of this library?

**Comment by basvandorst** [comment]
@MGatner: @vredeling already has the "admin"-permissions of this repo... 

To give someone 100% permissions of this repo we should consider the following options:
1. Handover this project to another (personal) repo. 
2. Create an organisation and move this project to the organisation
3. ... or leave it as is and let me know when you need specific permissions.

**Comment by MGatner** [comment]
It sounds like permissions are already in a good spot, these recent changes were just exceptions. That said I am always a fan of using an organization, because you never know when someone will become unavailable. That is largely up to you though, as the owner, and the other maintainers if they are willing to accept more responsibility. 

For me I am happy to help as long as my client needs the Strava API. This is a long-term contract, so pending a buyout or Strava kicking us off I plan to be with this project a while.
