### ISSUE TITLE
Webhook Subscriptions

### ISSUE THREAD

**Issue by MGatner** [basvandorst/StravaPHP#89]
The project I am working on needs Webhook subscriptions. The API actually has CRUD endpoints for [push subscriptions](https://developers.strava.com/docs/webhooks/). Would this library be interested in having these added? They function a little different vis-a-vis authentication because they exist at the service level (not individual accounts).

**Comment by vredeling** [comment]
Not sure, but if you need and supply it, I'll do a review. It won't be quick, but I'll check the work.
