### ISSUE TITLE
getSegmentLeaderboard not working

### ISSUE THREAD

**Issue by daankortenbach** [basvandorst/StravaPHP#91]
[SERVICE] Client error: GET https://www.strava.com/api/v3/segments/4420112/leaderboard?access_token=addtokenhere resulted in a 403 Forbidden response:
{"message":"Forbidden","errors":[]}

Wasted much time on this only to find out this isn't supported at all by Strava since 2 years ago!
https://developers.strava.com/docs/segment-changes/

**Comment by daankortenbach** [comment]
Hello?

**Comment by MGatner** [comment]
Hi 👋

**Comment by daankortenbach** [comment]
Is there any way around this? Assembling data to create a leaderboard?

**Comment by MGatner** [comment]
That doc you linked has the new endpoints and requires permissions. I wouldn't expect this SDK to adapt to those (unless you want to submit a PR yourself).
